defaults:
  - /backbone: ???
  - /target_predictor: transformer

name: gjepa
type: gjepa.models.GJEPANodeModel
ipe: 1.0
ipe_scale: 1.0
ema: [ 0.996, 1.0 ]
context_extractor_type: subgraph
target_extractor_type: subgraph
context_target_overlap_strategy: remove
transforms: { }
num_targets: 8
similarity_matrix_file: null
reload_dataloaders_every_n_epochs: 1
subgraph_method: cluster
