defaults:
  - dataset: ???
  - _self_

random_seed: ???
embedding_dim: ???
max_epochs: ???
hyperparameters:
  p: 1
  q: 1
  walk_length: 40
  context_size: 5
  walks_per_node: 10
embedding_file: data/pos_encodings/${.dataset.name}/node2vec.pt
metrics_file: data/node2vec_metrics/${.dataset.name}.json
