gnn_cls: gjepa.models.backbones.DimeNetEncoder
hidden_channels: 128
num_blocks: 4
num_radial: 6
num_spherical: 7
cutoff: 5.0
envelope_exponent: 5
num_before_skip: 1
num_after_skip: 2
num_output_layers: 3
num_bilinear: 8
max_num_neighbors: 16
disable_pos: false
out_dim: ${.hidden_channels}
