gnn_cls: gjepa.models.backbones.DummyModel
hidden_channels: 128
num_filters: 128
num_interactions: 4
num_gaussians: 50
cutoff: 5.0
max_num_neighbors: 16
disable_pos: false
out_dim: ${.hidden_channels}
