gnn_cls: gjepa.models.backbones.CustomGCN
in_channels: ${dataset.in_channels}
hidden_channels: [256, 256, 256]
out_dim: ${.hidden_channels[2]}
act: prelu
act_kwargs:
  num_parameters: 1
dropout: 0.0
norm: batch_norm
weights_standarization: false
plain_last: true
