name: ENZYMES
root_dir: data/datasets
pre_transforms: {}
transforms:
  NormalizeFeatures: {}
in_channels: 3
out_channels: 6
task_type: multiclass
main_metric: Accuracy
metric_mode: max
split_ratios: [0.8, 0.1]
