name: TMQM_SPECTO
root_dir: data/datasets/TMQM_SPECTO
pre_transforms: {}
transforms: 
  AddEdgesAndDistances:
    cutoff: 10.0
in_channels: 1
out_channels: 1
task_type: regression
predictor_kwargs:
  hidden_channels: null
  activation: null
  dropout: null
main_metric: MAE
metric_mode: min
split_ratios: [0.8, 0.1]
block_3_split_mode: null
group_by_isomers: true
additional_loading_params: 
  subset: "cv_vis"
  y_columns: ["HL_Gap"] #HOMO_Energy
  extra_fields: []
  
