name: TMQM_SPECTO
root_dir: data/datasets/TMQM_SPECTO
pre_transforms: {}
transforms: 
  AddEdgesAndDistances:
    cutoff: 10.0
in_channels: 1
out_channels: 370
task_type: multiregression
predictor_kwargs:
  hidden_channels: null
  activation: null
  dropout: null
split_ratios: [0.8, 0.1]
block_3_split_mode: null
group_by_isomers: true
metric_mode: min
main_metric: MAE
additional_loading_params: 
  prediction_type: vector
  vis_range: [350, 650]
  num_states: 4
  filter_type: one_visible_lambdas    #all_samples 
  block_3_only: True
  lorenzian: false
  sort_by_max_f: false
  min_f_value: -1
  filter_f_value: 0.001
  standarize_f: false
  standarize_lambda: false



  

