name: TMQM_SPECTO
root_dir: data/datasets/TMQM_SPECTO
pre_transforms: {}
transforms: 
  AddEdgesAndDistances:
    cutoff: 10.0
in_channels: 1
out_channels: 2
task_type: multiregression
predictor_kwargs:
  hidden_channels: null
  activation: null
  dropout: null
split_ratios: [0.8, 0.1]
block_3_split_mode: null
group_by_isomers: true
metric_mode: min
main_metric: MAE
additional_loading_params: 
  prediction_type: pairs
  num_states: 1
  vis_range: [350, 650]
  block_3_only: True
  filter_type: all_samples   # all_samples, all_visible_lambdas, one_visible_lambda
  min_f_value: -1
  filter_f_value: -1
  sort_by_max_f: false
  standarize_lambda: true
  standarize_f: true
  load_representations: null
  outlier_strategy: null
  convert_to_ev: false
  f_outlier_threshold: null
  lambda_outlier_threshold: null


