name: TMQM_SPECTO
root_dir: data/datasets/TMQM_SPECTO
pre_transforms: {}
transforms: 
  AddEdgesAndDistances:
    cutoff: 10.0
in_channels: 1
out_channels: 1
task_type: binary
predictor_kwargs:
  hidden_channels: null
  activation: null
  dropout: null
split_ratios: [0.8, 0.1]
block_3_split_mode: null
group_by_isomers: true
metric_mode: min
main_metric: loss  #AUROC  Accuracy
additional_loading_params: 
  prediction_type: binary_classification
  num_states: 1
  vis_range: [350, 650]
  block_3_only: True
  filter_type: all_samples    # all_samples
  filter_f_value: -1
  min_f_value: 0.01  # 0.05
  sort_by_max_f: false
  standarize_lambda: false
  standarize_f: false
  load_representations: ''
  outlier_strategy: whole-compound-outlier-removal
  convert_to_ev: false
  f_as_log10: false
  f_outlier_threshold: null # 0.5 null
  lambda_outlier_threshold: 1327.9505300000078  #null 1500
  
