name: TMQM_SPECTO
root_dir: data/datasets/TMQM_SPECTO
pre_transforms: {}
transforms: 
  AddEdgesAndDistances:
    cutoff: 5.0
in_channels: 1
out_channels: 20
task_type: multiregression
split_ratios: [0.8, 0.1]
metric_mode: min
main_metric: MAE
additional_loading_params: 
  prediction_type: pairs
  num_states: 10
  vis_range: [380, 750]
  filter_states: 10
  block_3_only: True
