name: TMQM_SPECTO
root_dir: data/datasets/TMQM_SPECTO
pre_transforms: {}
transforms: 
  AddEdgesAndDistances:
    cutoff: 5.0
in_channels: 1
prediction_type: vector
prediction_params:
  range: (280, 350)
  approximation: gaussian
task_type: regression
main_metric: MAE
metric_mode: min
split_ratios: [0.8, 0.1]
vis_range: [400, 700]
lambda: 10
subset: "cv_vis"

