name: WikiCS
root_dir: data/datasets
num_neighbors: [ 10, 10 ]
num_hops: 2
in_channels: 300
out_channels: 10
task_type: multiclass
main_metric: F1
metric_mode: max
pre_transforms:
  RandomNodeSplit: # drop the original split
    split: train_rest
    num_splits: 10
    num_val: 0.1
    num_test: 0.8
transforms: { }
num_partitions: 1_000 # used only when using subgraph_method = cluster, =~(#nodes / 10)
