# @package _global_

defaults:
  - override /training: training
  - override /dataset: roman_empire
  - override /pos_encoding: null
  - override /model: ???
  - override /backbone@model.backbone: hetero_sage_3_layer
