# @package _global_

defaults:
  - override /training: training
  - override /dataset: TMQM_SPECTO_PAIRS
  - override /pos_encoding: null
  - override /model: ???
  - override /backbone@model.backbone: gcn_2_layer
