# @package _global_

defaults:
  - override /training: training
  - override /dataset: TMQM_SPECTO_BINARY_VECTOR_MULTICLASS
  - override /pos_encoding: null
  - override /model: ???
  - override /backbone@model.backbone: gcn_2_layer
