# @package _global_

defaults:
  - override /training: training
  - override /dataset: ZINC
  - override /pos_encoding: null
  - override /model: ???
  - override /backbone@model.backbone: gcn_2_layer
