name: fourier_freq
file: data/pos_encoding/${dataset.name}/${.name}.pt
dim: 20
transforms:
  FourierFrequencyPE:
    attr_name: positional_encoding
    num_freqs: 10
    sigma: 1.0
    include_input: false
    random: true
