name: laplacian_3d
file: data/pos_encoding/${dataset.name}/${.name}.pt
dim: ${.transforms.AddLaplacianPE.k}
transforms:
  AddLaplacianPE:
    k: 8
    attr_name: positional_encoding
    cutoff: 5.0
    max_num_neighbors: 64

